### ISSUE TITLE
访问

### ISSUE THREAD

**Issue by Linuxbody** [pythonzm/blog#1]
大佬，我这部署了，怎么只能显示前端界面，后台不知道咋访问额
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/9931457/65653677-b62a3f80-e048-11e9-980e-57d8dbc69f3b.png">

**Comment by pythonzm** [comment]
后台访问地址在最后边儿的 / 加上admin就行了，README里忘记写了，你这个前端地址怎么有个admin？

**Comment by Linuxbody** [comment]
我也不知道额运行起来就这样子了
